// Generated by CoffeeScript 1.7.1
(function() {
  chrome.runtime.onMessage.addListener(function(request, sender, send_response) {
    if (sender.tab) {
      console.log("From a content script tab url: " + sender.tab.url);
      chrome.storage.sync.set({
        'url': sender.tab.url
      }, function() {
        return message("URL SAVED");
      });
      chrome.storage.sync.get('url', function(result) {
        return console.log("Get back from storage :" + result.url);
      });
    } else {
      console.log("From the extension");
    }
    if (request.greeting === "hello") {
      return sendResponse({
        farewell: "goodbye"
      });
    }
  });

}).call(this);
