// Generated by CoffeeScript 1.7.1
(function() {
  var popup_div;

  popup_div = void 0;

  document.addEventListener('keyup', function(evt) {
    var input_div, save_div;
    if (evt.keyCode === 83 && evt.ctrlKey === true) {

      /*
       * '<div id="octo-meme-save">
       *   <input id="octo-meme-tags" type="text" />
       * </div>'
       */
      console.log('Generate the popup.');
      if (popup_div) {

      } else {
        popup_div = document.createElement('div');
        popup_div.id = 'octo-meme-bg';
        save_div = document.createElement('div');
        save_div.id = 'octo-meme-save';
        input_div = document.createElement('input');
        input_div.id = 'octo-meme-tags';
        input_div.setAttribute('type', 'text');
        save_div.appendChild(input_div);
        popup_div.appendChild(save_div);
        document.body.appendChild(popup_div);
        return input_div.addEventListener('keyup', function(evt) {
          return console.log(evt.keyCode);
        });
      }
    }
  });

}).call(this);
